### ISSUE TITLE
Unable to install latest version from Cocoapods

### ISSUE THREAD

**Issue by danbtl** [SocketMobile/cocoapods-capturesdk#1]
Pods is requesting a password when attempting to install the latest version:
```bash
$ pod install
Analyzing dependencies
Downloading dependencies
Installing CaptureSDK (1.4.38)
git@git.socketmobile.com's password:
```

It seems like the git source URL was changed to an internal git repository in v1.4.35 in the following commit: https://github.com/SocketMobile/cocoapods-capturesdk/commit/7cc0d4b7f5f6b04ea909d189cbf5c8434562aef0

**Comment by jefflewis** [comment]
Verified as well. This public GitHub duplicate repo should be the source listed for it to be installable.

**Comment by BarryDuggan** [comment]
Verified as well 

```
ED25519 key fingerprint is SHA256:xnly9griObVyoLKMx20Qgdbl9Y5lq8YRNNE5GqLJwq0.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
git@git.socketmobile.com's password: 
```

**Comment by cyrille-socket** [comment]
Hi,
This has been fixed in https://github.com/SocketMobile/cocoapods-capturesdk/releases/tag/1.4.39
Sorry for the inconvenience. It should work now.
