### ISSUE TITLE
New releases Have No Notes

### ISSUE THREAD

**Issue by BarryDuggan** [SocketMobile/cocoapods-capturesdk#3]
In each tagged release there are no release notes describing what features have been added or what bugs have been resolved.
Would it be possible to so this going forward so that sdk consumers understand what they're upgrading to?

**Comment by cyrille-socket** [comment]
Hi @BarryDuggan,
we have the [Changelog](https://github.com/SocketMobile/cocoapods-capturesdk/blob/master/CHANGELOG.md) that reflects the changes.
